---
config:
    theme: 'default'
---
sequenceDiagram
    actor User
    participant Systemd as systemd
    participant PinSh as pin-usb-irq.sh
    participant OS as OS / Kernel

    %% Decoupled Boot Phase
    User->>OS: Reboot System
    Note over OS,Systemd: System boots into the selected kernel

    %% Service Execution Phase
    opt If pin-usb-irq.service is ENABLED
        Systemd->>+PinSh: ExecStart=/usr/local/bin/pin-usb-irq.sh
        
        PinSh->>+OS: echo 2 > /sys/.../eth0/queues/rx-0/rps_cpus (CPU 1)
        OS-->>-PinSh: return
        
        PinSh->>+OS: Find dwc2/dwc_otg in /proc/interrupts
        OS-->>-PinSh: Returns IRQ number
        PinSh->>+OS: echo 1 > /proc/irq/[IRQ]/smp_affinity (CPU 0)
        OS-->>-PinSh: return
        
        PinSh->>+OS: Find all 'irq/*' PIDs (Threaded IRQs)
        OS-->>-PinSh: return a list
        loop For each threaded IRQ PID
            PinSh->>+OS: taskset -cp 2 [PID] (Pin to CPU 2)
            OS-->>-PinSh: return
        end
        PinSh-->>-Systemd: RemainAfterExit=yes (Success)
    end
