---
config:
    theme: 'default'
---
%%{init: {'sequence': {'messageMargin': 15, 'boxMargin': 5, 'width': 10}}}%%
sequenceDiagram
    actor User
    participant Local as run_test.sh<br/>(Local Host)
    participant SSHStart as test_start.sh<br/>(Remote SSH)
    participant SystemD as systemd<br/>(Remote)
    participant TestExec as test-exec.service<br/>(Remote SSH)
    participant LedToggle as led-toggle.service<br/>(led-toggle)
    participant SSHState as test_state.sh<br/>(Remote SSH)

    User ->>+ Local: run_test.sh with parameters
    %% Parallel execution phase
    par Remote Profiling & Load for all scenarios
        %% in case of iperf3 usage
        Note over Local: Start network server (if needed)
        %% Start the remote execution (Headless hand-off)
        Local->>SSHStart: SSH exec: test_start.sh [args]
        Note over SSHStart: Write arguments to shared service-env-var file
        SSHStart->>SystemD: sudo systemctl start test-exec.service &
        SSHStart->>SystemD: sudo systemctl start led-toggle.service &
        SSHStart-->>Local: exit 0 (Returns immediately)

        SystemD->>+TestExec: ExecStart=test_exec.sh
        Note over Local: Start Python Saleae Capture script
        Note over TestExec: Register SYNC_WALL and SYNC_MONO start time
        SystemD->>+LedToggle: ExecStart=led-toggle
        Note over LedToggle: Toggle the pins
        
        Note over TestExec: Start profiling (cyclictest, mpstat, vmstat)<br/>Start load generators (fio, stress-ng, iperf3)
        Note over LedToggle: Write edge timestamp to csv file
        LedToggle-->>-SystemD: exit 0
        Note over Local: End Python Saleae Capture script
        Note over TestExec: Stop profiling & load Save remote logs
        Note over TestExec: Register SYNC_WALL and SYNC_MONO end time
        TestExec-->>-SystemD: exit 0
        
        loop (finished reponse not receved || timeout not reached)
            %% Synchronization phase
            Local->>+SSHState: SSH exec: test_state.sh
            SSHState-->>-Local: Send response (finished/failed/running)
        end

        %% in case of iperf3 usage
        Note over Local: Stop network server (if it was started)
    end
    
    %% Data collection
    Note over Local: scp remote logs to Local Host
    Note over Local: Run Python Results Processing script

    Local -->>- User: 
