---
  config:
    theme: 'default'
    gantt:
      sectionFontSize: 20
---
gantt
  title Measurement synchronization timings for a 10s test
  %% This is a comment
  axisFormat %S-%L
  dateFormat ss-SSS
  %% mtx - stands for margine time,
  %%       where x is an iterator
  %% ry_mtx - remote margine time
  %% ly_mtx - local margine time
  section remote
    %% Test execution script
    TE1 :rte1, 00-000, 10s
    MT  :rte_mt1, after rte1, 1s
    MT  :rte_mt2, after rte_mt1, 1s
    %% Commands running in test execution script
    CTE1:rcte1, 00-200, 10s
    MT  :rcte_mt1, after rcte1, 1s
    MT  :rcte_mt2, after rcte_mt1, 0.5s
    %% PIN toggle service
    MT  :rlt_mt1, 00-100, 1s
    LT1 :rlt1, after rlt_mt1, 10s
  section local
    M1  :lm1, 00-500, 10s
    MT  :lm_mt1, after lm1, 1s
    MT  :lm_mt2, after lm_mt1, 1s
  S1  : vert, vs1, 00-500, 1s
  S2  : vert, vs2, after lm_mt2, 1s
  L1  : vert, v1, after rlt_mt1, 1s
  L2  : vert, v2, after rlt1, 1s